### ISSUE TITLE
Move test vector generators in the root directory into zcash_test_vectors

### ISSUE THREAD

**Issue by daira** [zcash-hackworks/zcash-test-vectors#79]
orchard_*.py -> zcash_test_vectors/orchard
others -> zcash_test_vectors
Possibly add zcash_test_vectors/unified

**Comment by str4d** [comment]
I had left these files in place because I didn't want to complicate the refactor. But we should indeed refactor them to leverage the fact that poetry supports multiple scripts per file. So e.g. the `main()` function from `f4jumble_long.py` should become a `long_test_vectors()` function in `zcash_test_vectors/f4jumble.py`, and then we add the following line to `pyproject.toml`:

```
f4jumble_long = "zcash_test_vectors.f4jumble::long_test_vectors"
```
